### ISSUE TITLE
Unable to debug tests from yeoman generated angularjs website

### ISSUE THREAD

**Issue by digitalfuller** [iradul/vscode-phantomjs-debug#12]
## Unable to debug tests from yeoman generated angularjs website:

Hi, I'm unable to get any breakpoints hit when using the vanilla yeoman generated angularjs site.  I'm pretty new to this so there could be something I'm missing or unaware I need to do.

Cheers

### Environment

Windows 7 x64
node v6.9.4
npm 4.1.1

To scafold the site follow the instructions here:
https://github.com/yeoman/generator-angular

### Or the short version:
```
npm install -g grunt-cli bower yo generator-karma generator-angular
mkdir angular-debug
cd angular-debug
yo angular angular-debug
```

### yeoman selections:

```
? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? (Press <space> to select, <a> to toggle all, <i> to inverse selection)angular-animat
e.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
```

### install phantomjs
`npm install phantomjs-prebuilt`

### Open VS Code from the command prompt:
`code .`

### Follow the instructions from https://github.com/iradul/vscode-phantomjs-debug

Modify launch.json to look like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "phantomjs",
            "request": "launch",
            "file": "${file}",
            "webRoot": "${workspaceRoot}/app",
            "runtimeExecutable": "${workspaceRoot}/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe",
            "runtimeArgs": [],
            "sourceMaps": true,
            "verboseDiagnosticLogging": true
        }
    ]
}
```

### Select test/spec/controllers/main.js in VS Code

Put a breakpoint on the line (F9): expect(MainCtrl.awesomeThings.length).toBe(3);

### Run the "Launch" debug profile.

Allow PhantomJS.exe access through the Windows Firewall.

### Execution stops on an uncaught exception in main.js

Verbose logs are written to C:\Users\xxxx\.vscode\extensions\vscode-phantomjs-debug.txt
1:47:48 pm, 24/01/2017
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.1.0
From client: initialize({"adapterID":"phantomjs","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true}}
From client: launch({"name":"Launch","type":"phantomjs","request":"launch","file":"c:\\code\\angular-debug\\test\\spec\\controllers\\main.js","webRoot":"c:\\code\\angular-debug/app","runtimeExecutable":"c:\\code\\angular-debug/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe","runtimeArgs":[],"sourceMaps":true,"verboseDiagnosticLogging":true})
spawn('c:\code\angular-debug/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe', ["--remote-debugger-port=9222","c:\\code\\angular-debug\\test\\spec\\controllers\\main.js"])
HTTP - GET failed with: 404 - Not Found. The requested location could not be found.
To target: "{\"id\":1,\"method\":\"Debugger.enable\"}"
To target: "{\"id\":2,\"method\":\"Runtime.enable\"}"
To target: "{\"id\":3,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
To target: "{\"id\":4,\"method\":\"Runtime.run\"}"
To target: "{\"id\":5,\"method\":\"Console.enable\"}"
From target: {"result":{},"id":1}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"1","url":"phantomjs://code/main.js","startLine":0,"startColumn":0,"endLine":25,"endColumn":1}}
Paths.scriptParsed: could not resolve phantomjs://code/main.js to a file under webRoot: c:\code\angular-debug/app. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"2","url":"phantomjs://platform/bootstrap.js","startLine":0,"startColumn":0,"endLine":327,"endColumn":0}}
Paths.scriptParsed: could not resolve phantomjs://platform/bootstrap.js to a file under webRoot: c:\code\angular-debug/app. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"3","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":122}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"4","url":"phantomjs://platform/fs.js","startLine":0,"startColumn":0,"endLine":270,"endColumn":133}}
Paths.scriptParsed: could not resolve phantomjs://platform/fs.js to a file under webRoot: c:\code\angular-debug/app. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"5","url":"phantomjs://platform/system.js","startLine":0,"startColumn":0,"endLine":32,"endColumn":145}}
Paths.scriptParsed: could not resolve phantomjs://platform/system.js to a file under webRoot: c:\code\angular-debug/app. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"6","url":"phantomjs://platform/webpage.js","startLine":0,"startColumn":0,"endLine":895,"endColumn":148}}
Paths.scriptParsed: could not resolve phantomjs://platform/webpage.js to a file under webRoot: c:\code\angular-debug/app. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"isPageContext":true,"name":"","frameId":"0.1"}}}
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"isPageContext":false,"name":"file://","frameId":"0.1"}}}
From target: {"result":{},"id":2}
From target: {"error":{"code":-32601,"message":"'Runtime.runIfWaitingForDebugger' wasn't found"},"id":3}
From target: {"result":{},"id":4}
From target: {"result":{},"id":5}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From client: setBreakpoints({"source":{"path":"c:\\code\\angular-debug\\test\\spec\\controllers\\main.js","name":"main.js"},"lines":[21],"breakpoints":[{"line":21}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":21,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
To target: "{\"id\":6,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"uncaught\"}}"
From target: {"result":{},"id":6}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":6,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Thread 1"}]}}
To target: "{\"id\":7,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"__run()\",\"silent\":true,\"contextId\":1}}"
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"7","url":"","startLine":0,"startColumn":0,"endLine":1412,"endColumn":0}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"8","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":7}}
From target: {"method":"Debugger.paused","params":{"callFrames":[{"callFrameId":"{\"ordinal\":0,\"injectedScriptId\":1}","functionName":"__run","location":{"scriptId":"1","lineNumber":3,"columnNumber":0},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":1}","className":"Window","description":"Window"},"type":"local"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":2}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","value":null,"subtype":"null"}},{"callFrameId":"{\"ordinal\":1,\"injectedScriptId\":1}","functionName":"","location":{"scriptId":"8","lineNumber":0,"columnNumber":1},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":3}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":4}","className":"Window","description":"Window"}},{"callFrameId":"{\"ordinal\":2,\"injectedScriptId\":1}","functionName":"_evaluateOn","location":{"scriptId":"7","lineNumber":602,"columnNumber":13},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":5}","className":"Window","description":"Window"},"type":"local"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":6}","className":"Window","description":"Window"},"type":"closure"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":7}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":8}","className":"Object","description":"Object"}},{"callFrameId":"{\"ordinal\":3,\"injectedScriptId\":1}","functionName":"_evaluateAndWrap","location":{"scriptId":"7","lineNumber":521,"columnNumber":13},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":9}","className":"Window","description":"Window"},"type":"local"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":10}","className":"Window","description":"Window"},"type":"closure"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":11}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":12}","className":"Object","description":"Object"}},{"callFrameId":"{\"ordinal\":4,\"injectedScriptId\":1}","functionName":"evaluate","location":{"scriptId":"7","lineNumber":441,"columnNumber":9},"scopeChain":[{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":13}","className":"Window","description":"Window"},"type":"local"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":14}","className":"Window","description":"Window"},"type":"closure"},{"object":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":15}","className":"Window","description":"Window"},"type":"global"}],"this":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":16}","className":"Object","description":"Object"}}],"reason":"other"}}
To client: {"seq":0,"type":"event","event":"stopped","body":{"reason":"debugger statement","threadId":1}}
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":7,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Thread 1"}]}}
From client: stackTrace({"threadId":1,"startFrame":0,"levels":20})
To client: {"seq":0,"type":"response","request_seq":8,"command":"stackTrace","success":true,"body":{"stackFrames":[{"id":1000,"name":"__run","source":{"name":"main.js","sourceReference":1000},"line":3,"column":1},{"id":1001,"name":"(anonymous function)","source":{"name":"8","sourceReference":1001},"line":1,"column":2},{"id":1002,"name":"_evaluateOn","source":{"name":"7","sourceReference":1002},"line":603,"column":14},{"id":1003,"name":"_evaluateAndWrap","source":{"name":"7","sourceReference":1002},"line":522,"column":14},{"id":1004,"name":"evaluate","source":{"name":"7","sourceReference":1002},"line":442,"column":10}]}}
From client: source({"sourceReference":1000})
To target: "{\"id\":8,\"method\":\"Debugger.getScriptSource\",\"params\":{\"scriptId\":\"1\"}}"
From target: {"result":{"scriptSource":"function __run() {\n'use strict';\n\ndescribe('Controller: MainCtrl', function () {\n\n  // load the controller's module\n  beforeEach(module('angularDebugApp'));\n\n  var MainCtrl,\n    scope;\n\n  // Initialize the controller and a mock scope\n  beforeEach(inject(function ($controller, $rootScope) {\n    scope = $rootScope.$new();\n    MainCtrl = $controller('MainCtrl', {\n      $scope: scope\n      // place here mocked dependencies\n    });\n  }));\n\n  it('should attach a list of awesomeThings to the scope', function () {\n    expect(MainCtrl.awesomeThings.length).toBe(3);\n  });\n});\n\n}"},"id":8}
To client: {"seq":0,"type":"response","request_seq":9,"command":"source","success":true,"body":{"content":"function __run() {\n'use strict';\n\ndescribe('Controller: MainCtrl', function () {\n\n  // load the controller's module\n  beforeEach(module('angularDebugApp'));\n\n  var MainCtrl,\n    scope;\n\n  // Initialize the controller and a mock scope\n  beforeEach(inject(function ($controller, $rootScope) {\n    scope = $rootScope.$new();\n    MainCtrl = $controller('MainCtrl', {\n      $scope: scope\n      // place here mocked dependencies\n    });\n  }));\n\n  it('should attach a list of awesomeThings to the scope', function () {\n    expect(MainCtrl.awesomeThings.length).toBe(3);\n  });\n});\n\n}","mimeType":"text/javascript"}}
From client: scopes({"frameId":1000})
To client: {"seq":0,"type":"response","request_seq":10,"command":"scopes","success":true,"body":{"scopes":[{"name":"Local","variablesReference":1000,"expensive":false},{"name":"Global","variablesReference":1001,"expensive":true}]}}
From client: variables({"variablesReference":1000})
To target: "{\"id\":9,\"method\":\"Runtime.getProperties\",\"params\":{\"objectId\":\"{\\\"injectedScriptId\\\":1,\\\"id\\\":1}\",\"ownProperties\":false,\"accessorPropertiesOnly\":true,\"generatePreview\":true}}"
To target: "{\"id\":10,\"method\":\"Runtime.getProperties\",\"params\":{\"objectId\":\"{\\\"injectedScriptId\\\":1,\\\"id\\\":1}\",\"ownProperties\":true,\"accessorPropertiesOnly\":false,\"generatePreview\":true}}"
From target: {"result":{"result":[{"value":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":17}","subtype":"array","className":"Arguments","description":"Arguments[0]"},"writable":true,"enumerable":false,"configurable":true,"name":"arguments","isOwn":true}]},"id":9}
From target: {"result":{"result":[{"value":{"type":"object","objectId":"{\"injectedScriptId\":1,\"id\":18}","subtype":"array","className":"Arguments","description":"Arguments[0]"},"writable":true,"enumerable":false,"configurable":true,"name":"arguments","isOwn":true}]},"id":10}
To target: "{\"id\":11,\"method\":\"Runtime.callFunctionOn\",\"params\":{\"objectId\":\"{\\\"injectedScriptId\\\":1,\\\"id\\\":18}\",\"functionDeclaration\":\"function() { return [this.length, Object.keys(this).length - this.length]; }\",\"silent\":true,\"returnByValue\":true}}"
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"9","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":78}}
From target: {"result":{"result":{"type":"object","value":[0,0]},"wasThrown":false},"id":11}
To client: {"seq":0,"type":"response","request_seq":11,"command":"variables","success":true,"body":{"variables":[{"name":"this","value":"null","variablesReference":0},{"name":"arguments","value":"Arguments[0]","type":"Arguments[0]","variablesReference":1002,"indexedVariables":0,"namedVariables":0}]}}

**Comment by iradul** [comment]
That file `test/spec/controllers/main.js` cannot be loaded directly into PhantomJS:
```js
'use strict';
describe('Controller: MainCtrl', function () {

  // load the controller's module
  beforeEach(module('angularDebugApp'));

  var MainCtrl,
    scope;

  // Initialize the controller and a mock scope
  beforeEach(inject(function ($controller, $rootScope) {
    scope = $rootScope.$new();
    MainCtrl = $controller('MainCtrl', {
      $scope: scope
      // place here mocked dependencies
    });
  }));

  it('should attach a list of awesomeThings to the scope', function () {
    expect(MainCtrl.awesomeThings.length).toBe(3);
  });
});
```
PhantomJS just doesn't know what `describe` function is nor any other function used in the file.

Although you can still run the debugger but first you'll need to set `webRoot` to `${workspaceRoot}/test/spec/controllers` in your `launch.js` and then place breakpoint at the first line.

**Comment by iradul** [comment]
Seems like you want to debug JavaScript in page context not phantom's context.
I'm closing this issue since I didn't get any reply from you.
