### ISSUE TITLE
How to call debug sub modules? 

### ISSUE THREAD

**Issue by dfberry** [iradul/vscode-phantomjs-debug#4]
Hi, This isn't a bug against your package but I thought you might know the answer. I'm trying to debug into a sub-module (file). The explanation is here: [http://stackoverflow.com/questions/37624811/how-to-debug-secondary-files-of-phantomjs-in-vscode](http://stackoverflow.com/questions/37624811/how-to-debug-secondary-files-of-phantomjs-in-vscode)

I tried renaming the subdirectory to node_modules but it still doesn't debug into it. Do I have to have a flat  file structure in order for vs code to file the files?

**Comment by iradul** [comment]
I wrote an [explanation how to do it](https://github.com/iradul/vscode-phantomjs-debug/wiki/Debug-modules).
