### ISSUE TITLE
Replace forked Chrome debugger with vscode-chrome-debug-core

### ISSUE THREAD

**Issue by auchenberg** [iradul/vscode-phantomjs-debug#5]
This debugger is currently using a fork of the [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug), which makes it hard for this debugger to adapt bug fixes and improvements made in the new [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core) library.

A few months ago we separated the core debugger from [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug), which provides a generic Chrome debugger that's compliant to the Chrome Debugging Protocol, without specific runtime logic.

Today this core debugger is used by [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) and [vscode-edge-debug](https://github.com/Microsoft/vscode-edge-debug), and might be used for future Node.js debuggers too, as Node has adapted the same protocol.

You should consider replacing the current Chrome debugger with [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core)

**Comment by iradul** [comment]
Thanks!
I'll definitely do that.

**Comment by iradul** [comment]
Project is now based on [vscode-chrome-debug-core](https://github.com/Microsoft/vscode-chrome-debug-core), thanks again @auchenberg

**Comment by auchenberg** [comment]
Great @iradul! I've added your extension to our list! https://github.com/Microsoft/vscode-chrome-debug-core#debuggers-using-this-library

**Comment by iradul** [comment]
Awesome!

Hey @auchenberg I just checked it out, looks like you have a typo on _iOS Web Debugger_ link. If you don't want to fix it I can fork it to make it work though :smiley: 

![typo](https://cloud.githubusercontent.com/assets/2411422/19447031/b6da368e-9469-11e6-9c93-8f4dca10eeff.png)

**Comment by auchenberg** [comment]
Whoops, already fixed by a colleague of mine :)
