### ISSUE TITLE
debugging: doesn't stop at breakpoint

### ISSUE THREAD

**Issue by Theovanlaar** [iradul/vscode-phantomjs-debug#7]
Hello Iradul,

Thanks a lot for your Phantom add on. Installed it and everything seems to work ok. See debug console: success. 

When I place a breakpoint the debuggers doesn't stop and I can't step through the code. Can you give me a hint.

Best regards, 

![image](https://cloud.githubusercontent.com/assets/10544026/19388665/12465e12-9221-11e6-9358-f1b7ca50d547.png)
![image](https://cloud.githubusercontent.com/assets/10544026/19388673/1c0d7eb2-9221-11e6-9744-92efbd89ced6.png)

**Comment by iradul** [comment]
It's not clear but by looking at the images you provided I think your script name is `Testing.js` (with capital `T`) and `"file": "$(workspaceRoot)/testing.js"` is all low caps. You should have exact match as a matter of fact I would use low caps if possible.

**Comment by Theovanlaar** [comment]
Thanks iradul, need new glasses :)
